spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hardware_deals_dev
    username: postgres
    password: postgres
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    root: INFO
    com.hardwaredeals: DEBUG
    org.springframework.web: DEBUG
